name: DevSecOps Pipeline - only zap
on:
  - pull_request
  - workflow_dispatch
jobs: 
  zap_scan:
    runs-on: ubuntu-latest
    permissions: write-all
    name: zap
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.13.0
        with:
          target: 'http://juice-shop.herokuapp.com/'
